name: 'Terraform Init'
 
on:
  repository_dispatch:
    types: [build_workflow]
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: master
      deploy_message:
        description: Deploy Description
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      DISPATCH_URL: https://api.github.com/repos/rahulmalewadi/terraform-azure/dispatches

    runs-on: ubuntu-latest
    environment: production
 
   
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./src"
         
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./src"

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./src"
    #- name: Setup Python
     # uses: actions/setup-python@v2.2.2
    #- name: install python packages
     # run: |
     #  python -m pip install --upgrade pip

     
   # - name: install python packages    
       
    #  run: python api.py
      #this api post request not working   
    - name: run second file by repo-dispatch 
      run: |
        #chmod +x apiReq.sh
         curl -XPOST -u "${{secrets.GIT_USER}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" ${{secrets.GIT_REQ_URL}} --data '{"event_type": "deploy_workflow"}'
        #./apiReq.sh
      

      

 

      

  
